### ISSUE TITLE
Issue: Link Prefix in dot core install variable error

### ISSUE THREAD

**Issue by yacosta738** [gtrabanco/dotSloth#207]
dot core install                                                                               ✔ 
docopts:error: Print_bash_global:--link-prefix: two or more elements have identically mangled names
/home/acosta/.dotfiles/modules/sloth/scripts/core/install: line 88: link_prefix: unbound variable

**Comment by gtrabanco** [comment]
Thanks for the report.

This is due to the same name between two variables in docpars which could not be detected because I always debugged by using `DOTLY_INSTALLER=1` env var when excuting `dot core install`.

Thanks to this report was also detected that `--link-prefix` was ignored and the linking was done always to `/usr/local/bin`.

This is solved and fix will be merges shortly.

Regards!
